/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import awsconfig from "./aws-exports";
const awsmobile = {
  aws_project_region: "ap-south-1",
};

export default awsmobile;
